repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.286
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.10
        args:
          - "--line-length=100"
  - repo: local
    hooks:
      - id: pytest
        name: Pytest and Coverage
        description: 100% unit testing coverage for Python code.
        entry: make test_cli
        language: system
        pass_filenames: false
        always_run: true
        types: [python]
